### ISSUE TITLE
How to add external fonts

### ISSUE THREAD

**Issue by hani-lengxi** [M3351AN/saphire#2]
How to add external fonts

**Comment by hani-lengxi** [comment]
I want to change it to Chinese, but the font in the Windows/FONT folder will be blank

**Comment by M3351AN** [comment]
![GTTUOC3L$6)JN6`I`Q(M H4](https://user-images.githubusercontent.com/65479796/211165807-4650b144-2e6e-408b-bffd-8f1eaabe9130.JPG)
![2H8MZJXZR6NG~$3 5$R2V$J](https://user-images.githubusercontent.com/65479796/211165812-a0dddaf6-8392-4ab6-b734-8f0f16b97d58.JPG)
![T} _O0 JZT`QJMNPN949)%4](https://user-images.githubusercontent.com/65479796/211165823-3e421a54-bbb5-4565-abe3-979bfe3d2e93.png)
![W(DZUPPO@BA Y @XR@A~QCV](https://user-images.githubusercontent.com/65479796/211165829-46817356-ece0-4636-91d0-3da47d5b2ce2.png)
I think u already get the answer, so these may be useul for sb. else have the similiar issue
